// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:

        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxtGnuUmwg2CICMU_bzPAhXFRZg_f5h5Q',
    appId: '1:614869463438:web:ed2b09f16977d29acbf4df',
    messagingSenderId: '614869463438',
    projectId: 'foodcourt-5775b',
    authDomain: 'foodcourt-5775b.firebaseapp.com',
    databaseURL: 'https://foodcourt-5775b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodcourt-5775b.appspot.com',
    measurementId: 'G-52F7NC0FSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvd8moTqK4MpE_aezfFTZV65a3ayMhKsQ',
    appId: '1:614869463438:android:cbb2e3969465c6bccbf4df',
    messagingSenderId: '614869463438',
    projectId: 'foodcourt-5775b',
    databaseURL: 'https://foodcourt-5775b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodcourt-5775b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmn5pEKPta3ABgst7rrjh-kbO3hWtE8A4',
    appId: '1:614869463438:ios:2310bc365e7ba3a6cbf4df',
    messagingSenderId: '614869463438',
    projectId: 'foodcourt-5775b',
    databaseURL: 'https://foodcourt-5775b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'foodcourt-5775b.appspot.com',
    iosClientId: '614869463438-rei1s0lqm4bsnubhtp5bi1momr0c5euq.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodcourt',
  );
}
